name: 'Test in docker container'
description: 'Runs npm test within a docker container'
inputs:
  workspace:
    description: 'Workspace directory'
    required: true
runs:
  using: 'docker'
  image: "${{ inputs.workspace }}/Dockerfile"
  entrypoint: "npm"
  args:
    - run
    - test
